services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ak-web
    ports:
      - "${WEB_PORT:-8080}:8080"
    volumes:
      - ./web:/var/www/air-khorasan/web
    depends_on:
      - api
      - database
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ak-api
    ports:
      - "${API_PORT:-8000}:80"
    volumes:
      - ./api:/var/www/air-khorasan/api
    depends_on:
      - database
  database:
    image: mysql:8.0
    container_name: ak-mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-air-khorasan}
      MYSQL_USER: ${MYSQL_USER:-khorasan}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootsecret}

volumes:
  mysql-db: